// Date: 2/20/2018 8:41:25 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer safe;
    ModelRenderer lid;
    ModelRenderer post;
    ModelRenderer handle1;
    ModelRenderer handle2;
    ModelRenderer latch1;
    ModelRenderer latch2;
    ModelRenderer hinge1;
    ModelRenderer hinge2;
    ModelRenderer foot1;
    ModelRenderer foot2;
    ModelRenderer foot3;
    ModelRenderer foot4;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      safe = new ModelRenderer(this, 0, 0);
      safe.addBox(0F, 0F, -9F, 12, 12, 9);
      safe.setRotationPoint(-6F, 11F, 6F);
      safe.setTextureSize(64, 32);
      safe.mirror = true;
      setRotation(safe, 0F, 0F, 0F);
      lid = new ModelRenderer(this, 0, 22);
      lid.addBox(0F, 0F, -3F, 10, 12, 3);
      lid.setRotationPoint(-6F, 11F, -3F);
      lid.setTextureSize(64, 32);
      lid.mirror = true;
      setRotation(lid, 0F, 0F, 0F);
      post = new ModelRenderer(this, 43, 0);
      post.addBox(0F, 0F, 0F, 2, 12, 3);
      post.setRotationPoint(4F, 11F, -6F);
      post.setTextureSize(64, 32);
      post.mirror = true;
      setRotation(post, 0F, 0F, 0F);
      handle1 = new ModelRenderer(this, 27, 22);
      handle1.addBox(-3.5F, -0.5F, -1F, 7, 1, 1);
      handle1.setRotationPoint(-1F, 17F, -6F);
      handle1.setTextureSize(64, 32);
      handle1.mirror = true;
      setRotation(handle1, 0F, 0F, 0F);
      handle2 = new ModelRenderer(this, 27, 25);
      handle2.addBox(-0.5F, -3.5F, -1F, 1, 7, 1);
      handle2.setRotationPoint(-1F, 17F, -6F);
      handle2.setTextureSize(64, 32);
      handle2.mirror = true;
      setRotation(handle2, 0F, 0F, 0F);
      latch1 = new ModelRenderer(this, 33, 25);
      latch1.addBox(-1F, 0F, -1F, 3, 1, 1);
      latch1.setRotationPoint(4F, 12F, -6F);
      latch1.setTextureSize(64, 32);
      latch1.mirror = true;
      setRotation(latch1, 0F, 0F, 0F);
      latch2 = new ModelRenderer(this, 33, 28);
      latch2.addBox(-1F, 0F, -1F, 3, 1, 1);
      latch2.setRotationPoint(4F, 21F, -6F);
      latch2.setTextureSize(64, 32);
      latch2.mirror = true;
      setRotation(latch2, 0F, 0F, 0F);
      hinge1 = new ModelRenderer(this, 54, 0);
      hinge1.addBox(0F, 0F, 0F, 1, 3, 1);
      hinge1.setRotationPoint(-7F, 12F, -3F);
      hinge1.setTextureSize(64, 32);
      hinge1.mirror = true;
      setRotation(hinge1, 0F, 0F, 0F);
      hinge2 = new ModelRenderer(this, 54, 5);
      hinge2.addBox(0F, 0F, 0F, 1, 3, 1);
      hinge2.setRotationPoint(-7F, 19F, -3F);
      hinge2.setTextureSize(64, 32);
      hinge2.mirror = true;
      setRotation(hinge2, 0F, 0F, 0F);
      foot1 = new ModelRenderer(this, 43, 16);
      foot1.addBox(0F, 0F, 0F, 2, 1, 2);
      foot1.setRotationPoint(4F, 23F, -6F);
      foot1.setTextureSize(64, 32);
      foot1.mirror = true;
      setRotation(foot1, 0F, 0F, 0F);
      foot2 = new ModelRenderer(this, 43, 16);
      foot2.addBox(0F, 0F, 0F, 2, 1, 2);
      foot2.setRotationPoint(4F, 23F, 4F);
      foot2.setTextureSize(64, 32);
      foot2.mirror = true;
      setRotation(foot2, 0F, 0F, 0F);
      foot3 = new ModelRenderer(this, 43, 16);
      foot3.addBox(0F, 0F, 0F, 2, 1, 2);
      foot3.setRotationPoint(-6F, 23F, -6F);
      foot3.setTextureSize(64, 32);
      foot3.mirror = true;
      setRotation(foot3, 0F, 0F, 0F);
      foot4 = new ModelRenderer(this, 43, 16);
      foot4.addBox(0F, 0F, 0F, 2, 1, 2);
      foot4.setRotationPoint(-6F, 23F, 4F);
      foot4.setTextureSize(64, 32);
      foot4.mirror = true;
      setRotation(foot4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    safe.render(f5);
    lid.render(f5);
    post.render(f5);
    handle1.render(f5);
    handle2.render(f5);
    latch1.render(f5);
    latch2.render(f5);
    hinge1.render(f5);
    hinge2.render(f5);
    foot1.render(f5);
    foot2.render(f5);
    foot3.render(f5);
    foot4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
