// Date: 2/1/2018 11:58:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelChest extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Lid;
    ModelRenderer padBottom;
    ModelRenderer Latch1;
    ModelRenderer Latch2;
    ModelRenderer Latch3;
    ModelRenderer padTop;
    ModelRenderer hingeBottom1;
    ModelRenderer hingeBottom2;
  
  public ModelChest()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 0, 21);
      Base.addBox(-7F, 0F, -14F, 14, 10, 14);
      Base.setRotationPoint(0F, 14F, 7F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Lid = new ModelRenderer(this, 0, 0);
      Lid.addBox(-7F, -5F, -14F, 14, 5, 14);
      Lid.setRotationPoint(0F, 15F, 7F);
      Lid.setTextureSize(64, 32);
      Lid.mirror = true;
      setRotation(Lid, 0F, 0F, 0F);
      padBottom = new ModelRenderer(this, 7, 47);
      padBottom.addBox(-2F, 0F, -1F, 4, 3, 1);
      padBottom.setRotationPoint(0F, 15F, -6F);
      padBottom.setTextureSize(64, 32);
      padBottom.mirror = true;
      setRotation(padBottom, 0F, 0F, 0F);
      Latch1 = new ModelRenderer(this, 0, 47);
      Latch1.addBox(-1F, -2F, -15F, 2, 4, 1);
      Latch1.setRotationPoint(0F, 15F, 7F);
      Latch1.setTextureSize(64, 32);
      Latch1.mirror = true;
      setRotation(Latch1, 0F, 0F, 0F);
      Latch2 = new ModelRenderer(this, 0, 47);
      Latch2.addBox(0F, -2F, -8F, 1, 4, 2);
      Latch2.setRotationPoint(7F, 15F, 7F);
      Latch2.setTextureSize(64, 32);
      Latch2.mirror = true;
      setRotation(Latch2, 0F, 0F, 0F);
      Latch3 = new ModelRenderer(this, 0, 47);
      Latch3.addBox(-1F, -2F, -8F, 1, 4, 2);
      Latch3.setRotationPoint(-7F, 15F, 7F);
      Latch3.setTextureSize(64, 32);
      Latch3.mirror = true;
      setRotation(Latch3, 0F, 0F, 0F);
      padTop = new ModelRenderer(this, 18, 47);
      padTop.addBox(-2F, -3F, -14F, 4, 3, 1);
      padTop.setRotationPoint(0F, 15F, 7F);
      padTop.setTextureSize(64, 32);
      padTop.mirror = true;
      setRotation(padTop, 0F, 0F, 0F);
      hingeBottom1 = new ModelRenderer(this, 29, 47);
      hingeBottom1.addBox(-1F, 0F, -1F, 2, 2, 1);
      hingeBottom1.setRotationPoint(3F, 14F, 7F);
      hingeBottom1.setTextureSize(64, 32);
      hingeBottom1.mirror = true;
      setRotation(hingeBottom1, 0F, 0F, 0F);
      hingeBottom2 = new ModelRenderer(this, 29, 47);
      hingeBottom2.addBox(-1F, -1F, -1F, 2, 2, 1);
      hingeBottom2.setRotationPoint(-3F, 15F, 7F);
      hingeBottom2.setTextureSize(64, 32);
      hingeBottom2.mirror = true;
      setRotation(hingeBottom2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Lid.render(f5);
    padBottom.render(f5);
    Latch1.render(f5);
    Latch2.render(f5);
    Latch3.render(f5);
    padTop.render(f5);
    hingeBottom1.render(f5);
    hingeBottom2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
