// Date: 2/4/2018 12:50:09 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer Group1;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("Group1.Box1", 0, 0);
    setTextureOffset("Group1.Box2", 0, 0);
    
    Group1 = new ModelRenderer(this, "Group1");
    Group1.setRotationPoint(0F, 3F, 0F);
    setRotation(Group1, 0F, 0F, 0F);
    Group1.mirror = true;
      Group1.addBox("Box1", -5F, -2F, -1F, 8, 4, 1);
      Group1.addBox("Box2", -2F, 0F, -4F, 4, 4, 4);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Group1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
